In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print("Original array:", arr)
print("Shape of the original array:", arr.shape)


Original array: [1 2 3 4 5 6]
Shape of the original array: (6,)


In [2]:
arr_reshaped = arr.reshape(2, 3)
print("Reshaped array (2 rows, 3 columns):")
print(arr_reshaped)
print("Shape of the reshaped array:", arr_reshaped.shape)


Reshaped array (2 rows, 3 columns):
[[1 2 3]
 [4 5 6]]
Shape of the reshaped array: (2, 3)


In [3]:
arr_reshaped = arr.reshape(1, -1)
print("Reshaped array (1 row, inferred columns):")
print(arr_reshaped)
print("Shape of the reshaped array:", arr_reshaped.shape)


Reshaped array (1 row, inferred columns):
[[1 2 3 4 5 6]]
Shape of the reshaped array: (1, 6)


In [4]:
arr_reshaped = arr.reshape(-1, 2)
print("Reshaped array (inferred rows, 2 columns):")
print(arr_reshaped)
print("Shape of the reshaped array:", arr_reshaped.shape)


Reshaped array (inferred rows, 2 columns):
[[1 2]
 [3 4]
 [5 6]]
Shape of the reshaped array: (3, 2)


In [5]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Original 2D array:")
print(arr_2d)
print("Shape of the original 2D array:", arr_2d.shape)


Original 2D array:
[[1 2 3 4]
 [5 6 7 8]]
Shape of the original 2D array: (2, 4)


In [10]:
arr_3d = arr_2d.reshape(2, 2, 2)
print("Reshaped array to 3D (2x2x2):")
print(arr_3d)
print("Shape of the reshaped 3D array:", arr_3d.shape)


Reshaped array to 3D (2x2x2):
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape of the reshaped 3D array: (2, 2, 2)
